
// Login constants
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_CHECK = 'LOGIN_CHECK'
export const LOGIN_CHECK_LOADING = 'LOGIN_CHECK_LOADING'
export const LOGIN_CHECK_SUCCESS = 'LOGIN_CHECK_SUCCESS';
export const LOGIN_CHECK_FAILED = 'LOGIN_CHECK_FAILED';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS';
export const GET_ALL_TEAMS_FAILED = 'GET_ALL_TEAMS_FAILED';


export const SELECT_TEAM = 'SELECT_TEAM';

export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAILED = 'GET_CHANNELS_FAILED';